version: 2
jobs:
  build:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          make linux-debug
  test:
    docker:
      - image: ossrs/srs:dev
    steps:
      - checkout
      - run: |
          ln -sf /usr/local/gtest utest/gtest &&
          make linux-debug-gcov &&
          ./obj/st_utest && bash auto/codecov.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
